apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app.name}
  labels:
    app: nginx
spec:
  replicas: ${replica.count}
  selector:
    matchLabels:
      app: ${app.name}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
         Secret:  nginx-secret
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Secret
metadata:
  name: nginx-secret
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80